### ISSUE TITLE
Export results in error ENOENT: No such file or directory, open 'null/Movements.json'

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-model-interchange#10]
When I try to export modelinterchange for this [file
](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj) I get an error: ENOENT: No such file or directory, open 'null/Movements.json'

**Comment by faizanvahevaria** [comment]
@Fak3 
Here i have attached screen recording (record.zip) of model-interchange export and exported file in (Movements.zip) file for the this [file ](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj)
[record.zip](https://github.com/gs-gs/staruml-model-interchange/files/4053689/record.zip)

[Movements.zip](https://github.com/gs-gs/staruml-model-interchange/files/4053707/Movements.zip)

**Comment by Fak3** [comment]
Ah! This happened because Staruml was previously terminated without saving the file and then when I started and opened same file it said that it is restored from auto-save.
It is a rare case, so may not be that important for now

**Comment by faizanvahevaria** [comment]
So please close this ticket if not important for now

**Comment by Fak3** [comment]
It is more appropriate to add a label "Priority:Low"

**Comment by faizanvahevaria** [comment]
> It is more appropriate to add a label "Priority:Low"

I did not understand. Can you elaborate ?

**Comment by Fak3** [comment]
The issue here is a rare case, so we can set a lower priority, and only fix if there is no more urgent tasks. So we can create a github label for such issue.

**Comment by faizanvahevaria** [comment]
ok

**Comment by faizanvahevaria** [comment]
@kshychko & @Fak3 
I request to  close this ticket and reopen when this issue raise again

**Comment by faizanvahevaria** [comment]
please test this ticket too and close if it is resolved

**Comment by faizanvahevaria** [comment]
I have tested and not able to raise this issue so i am closing this ticket for now
