### ISSUE TITLE
Import results in few errors

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-model-interchange#11]
When i export the interchange json for this [file](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj), then i create new empty staruml file and import the interchange file back, i am getting quite a few errors like this: 
![Screenshot_20200114_010005](https://user-images.githubusercontent.com/991641/72295647-0ca7a200-3669-11ea-927b-e4ff56211483.jpeg)

Why am I getting these errors when i import, but did not see any errors when i performed an export earlier? I think It should give the errors\warnings when i export, if there are any such errors which won't allow me to correctly import this file afterwards.

Then when i try to drag `TransportMovement` to the diagram, it does not get added, but some other entities like Voyage can be added by dragging it to the canvas.

**Comment by faizanvahevaria** [comment]
![download](https://user-images.githubusercontent.com/15009067/73155568-259c6280-4101-11ea-8847-a614a778fba6.png)

Hello @Fak3 
In the screenshot, I had discussed with @onthebreeze. 
So its a **RULE** If we use any class from other package ( For example : 'TransportParty' class is inherited from 'Party' package from this [file](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj). So, Those classes should be abstract as indicated in scheenshot.
So, I made 'isAbstract' property 'true' of 'TransportParty' class in 'Party' package.
Please follow this rule. Then  export and import.

One more thing, model interchange extension will not export **diagram**. So, when you will follow above instruction and import it in new file, only classes and packages will be imported.

**Comment by Fak3** [comment]
> So, I made 'isAbstract' property 'true' of 'TransportParty' class in 'Party' package. Please follow this rule. Then export and import.

Ok, i just did that. Now i don't get the errors when i import the file.

But two issues still persist:

1) If a class is missing _isAbstract_ property, we should generate a warning when the user exports the interchange file, but not when it imports.

2) I am still unable to add `TransportMovements` to the diagram - when i drag and drop it to the canvas nothing happens.

**Comment by faizanvahevaria** [comment]
@Fak3 
Please close this ticket if this is fine

**Comment by Fak3** [comment]
fixed
