### ISSUE TITLE
The default class diagram shoudn't be generated for big projects

### ISSUE THREAD

**Issue by kshychko** [gs-gs/staruml-model-interchange#13]
When a project in interchange format doesn't have a class diagram and does have 10+ classes, I don't think we need to generate the default class diagram. It's too big and impossible to work with.

**Comment by faizanvahevaria** [comment]
@kshychko 
Latest code is updated to master

**Comment by kshychko** [comment]
@faizanvahevaria , works for me, closing the issue.
