### ISSUE TITLE
Parent ref for classes points to class diagramm insetad of the package

### ISSUE THREAD

**Issue by kshychko** [gs-gs/staruml-model-interchange#14]
When the project is generated from the file in interchange format, classes are added as elements of "ownedElements" array of the package, but their parent ref points to the class diagram. That's makes impossible to move classes between packages.

**Comment by kshychko** [comment]
[sample-from-icf-wrong-parent-ref.zip](https://github.com/gs-gs/staruml-model-interchange/files/4286477/sample-from-icf-wrong-parent-ref.zip)
For the reference.

**Comment by faizanvahevaria** [comment]
@kshychko 
I see parent ref point of both 'PersonIdentityDocumentDetailsList' and 'PersonIdentityDocumentDetails' class is (from Root) in sample-from-icf-wrong-parent-ref model file.
Can you please send me the interchange file which you have imported.

**Comment by kshychko** [comment]
[icf-wrong-parent-ref.zip](https://github.com/gs-gs/staruml-model-interchange/files/4290000/icf-wrong-parent-ref.zip)
Please find the source file here. Looks like the attached mdj file uml classes are referring to a parent which doesn't exist.

**Comment by faizanvahevaria** [comment]
@kshychko 
Latest code is updated to master

**Comment by kshychko** [comment]
@faizanvahevaria , the fix works for me. Closing the issue.
