### ISSUE TITLE
Add package to the source ant target properties of Relationship object

### ISSUE THREAD

**Issue by kshychko** [gs-gs/staruml-model-interchange#16]
The same class names are allowed when they are in different packages. We need to specify package in source/target properties to differentiate the classes with the same name from different packages.
 
[same-class-name.zip](https://github.com/gs-gs/staruml-model-interchange/files/4313849/same-class-name.zip)

This zip contains a sample StarUML project with three packages:
Package1 contains class ClassName0
Package2 contains class ClassName1
Package3 contains class ClassName1
ClassName0 has two relationships to the both classes from Package2 and  Package3.
The expected result - dependent array has two items, actual result - only ClassName1 from Package2 is included.
I expected adding package property to source/target solving the problem.

**Comment by faizanvahevaria** [comment]
> The expected result - dependent array has two items, actual result - only ClassName1 from Package2 is included.

Hi @kshychko 
The rule of composition and aggregation is that the dimond shape should be at source side and in your mdj file relationship between Class0(from Package1) and Class1(from Package3) where Class0 is target and Class1 is source. So even Class1 is being abstract is not exported as dependent.
So, i made changes in mdj file which is attached below
[changed_same-class-name.zip](https://github.com/gs-gs/staruml-model-interchange/files/4322639/changed_same-class-name.zip)

Rules for association relationship : 
Aggregation : end1.aggregation='shared' && end2.aggregation='none'
Composition : end1.aggregation='composition' && end2.aggregation='none'
Association : end1.aggregation='none' && end2.aggregation='none'

I have added 'package' property to source/target object for aggregation, composition and association.

**Comment by faizanvahevaria** [comment]
latest code is updated in version 0.1.5

**Comment by kshychko** [comment]
Can see package property in the exported file and the behaviour described in this ticket wasn't reproduced. Closing the issue.
