### ISSUE TITLE
Target entities can not be found during the first import

### ISSUE THREAD

**Issue by kshychko** [gs-gs/staruml-model-interchange#17]
When I import the attached file I get the errors about target entities. When I import the same file the second times, the errors are not show and the missing properties are added.
Check `ApplicationRelatedSponsorshipMsg` class after the first import - there will be only two relationships. Check it after the second import - the third relationship `BirthDate` is added.
[visa-icf.zip](https://github.com/gs-gs/staruml-model-interchange/files/4314025/visa-icf.zip)

**Comment by faizanvahevaria** [comment]
@kshychko 
Please regenerate file (visa-icf.json) updating latest code #16 
I could not imprt visa-icf.json because in that json file 

> "type": "Package",
>   "name": "vsa",

which should be 

> "type": "package",
>   "name": "vsa",

**Comment by kshychko** [comment]
@faizanvahevaria , please find the updated file attached. I adjusted the type value for packages and added package properties to soure/target objects. Issue is still reproducible.
[visa-icf-updated.zip](https://github.com/gs-gs/staruml-model-interchange/files/4328954/visa-icf-updated.zip)

**Comment by faizanvahevaria** [comment]
latest code is updated in version 0.1.5

**Comment by kshychko** [comment]
Fixed, closing the issue.
