### ISSUE TITLE
Can't see any menu under tools after installed

### ISSUE THREAD

**Issue by oslivan** [gs-gs/staruml-model-interchange#18]
I manually installed model-interchange, but after success, and then restart my staruml, I never find it. My staruml version is v2.8.1, does it be supported?

**Comment by faizanvahevaria** [comment]
I tried downgrading Staruml to 0.8.1 and it is showing me "Unknown installation error API_NOT_COMPATIBLE"
Please upgrade your starUML 3.0.0 and greater

**Comment by oslivan** [comment]
Get it, thanks for your reply!

**Comment by faizanvahevaria** [comment]
Your welcome
